	<div class="container_12 clearfix content">
		<div class="grid_6">
			<div class="box">
				<h3>Registrate</h3>
				<div class="box-content">
					<form action="login/registrar">
						<input type="text" placeholder="Correo" name="email">
						<input type="password" placeholder="Contraseña" name="pass">
						<input type="password" placeholder="Confirma tu contraseña" name="passagain">
						<input type="text" placeholder="Nombre" name="name" class="bigger_margin">
						<p class="smaller_margin"><label for="newsletter" class="custom_checkbox"><input type="checkbox" name="newsletter" id="newsletter"> Quiero recibir actualizaiones y promociones.</label></p>
						<p><label for="terms" class="custom_checkbox"><input type="checkbox" name="terms" id="terms">Acepto los <a href="#">terminos y condiciones</a> y tambien las <a href="#">politicas de provacidad</a>.</label></p>
						<p class="centered_content"><a class="button submit red">Registrarme</a></p>
					</form>
				</div>
			</div>
		</div>
		<div class="grid_6">
			<div class="box">
				<h3>Ingresa</h3>
				<div class="box-content clearfix">
					<form action="login/ingresar">
						<input type="text" placeholder="Correo" name="email">
						<input type="password" placeholder="Contraseña" name="pass">
						<label for="remember_me" class="custom_checkbox remember_me"><input type="checkbox" name="remember_me" id="remember_me">Recordarme</label>
						<a class="button submit red right">Entrar</a>
						<a href="#" class="forgotten_pass right">¿Olvidaste tu contraseña?</a>
					</form>
				</div>
			</div>
			<div class="box">
				<h3>Facebook</h3>
				<div class="box-content">
					<p class="centered_content"><a href="login/facebook" class="button facebook wider">Ingresar con Facebook</a></p>
				</div>
			</div>
		</div>
	</div>

	<div class="container_12 clearfix" id="add_new_item_info">
            
			<div class="grid_8 bigger_margin">
                            <form action="publicar/subirImagen" id="as" enctype="multipart/form-data">
				<div class="box clearfix">
                                    <h3>Informaci&oacute;n del vehiculo</h3>
					<div class="box-content clearfix bordered_under">
						<div class="half left">
							<p>
								<label for="type" class="dropdown_label">Tipo</label>
								<select name="tipo" id="tipo" class="custom_select">
                                                                    <?php foreach ($this->objTipos  as $obj) { 
                                                                              echo '<option value="'.$obj->getIdTipo().'">'.$obj->getNombre().'</option>';
                                                                     } ?>
								</select>
							</p>
							<p class="smaller_margin">
								<label for="condition_new" class="custom_radio"><input type="radio" name="condition" id="condition_new" value="new">Nuevo</label>
								<label for="condition_used" class="custom_radio"><input type="radio" name="condition" id="condition_used" value="used">Usado</label>
							
                                                        </p>
						</div>
                       
						<div class="half right">
							<p>
								<label for="category" class="dropdown_label">Carroceria</label>
								<select name="carroceria" id="carroceria" class="custom_select">
                                                                    <?php   foreach ($this->objCarrocerias  as $obj) { 
                                                                           echo '<option value="'.$obj->getIdCarroceria().'">'.$obj->getNombre().'</option>';
                                                                       } ?>
								</select>
							</p>
						</div>
                                                
					</div>
                                        <div class="box-content clearfix bordered_under">
						<div class="half left">
							<p>
								<label for="marca" class="dropdown_label">Marca</label>
								<select name="marca" id="type" class="custom_select">
                                                                    <?php   foreach ($this->objMarcas  as $obj) { 
                                                                                echo '<option value="'.$obj->getIdMarca().'">'.$obj->getNombre().'</option>';
                                                                            } ?>
								</select>
							</p>
                                                        <p>
								<label for="category" class="dropdown_label">Modelo</label>
								<input type="text" placeholder="ej. Swift" name="Modelo">
							</p>
                                                        <p>
								<label for="brand" class="dropdown_label">Patente</label>
								<input type="text" placeholder="ej. AB1234" name="Modelo">
							</p>
                                                        <p>
								<label for="brand" class="dropdown_label">Año</label>
								<input type="text" placeholder="ej. 2007" name="Modelo">
							</p>
						</div>
                       
						<div class="half right">
                                                        <p>
								<label for="marca" class="dropdown_label">Año</label>
								<select name="marca" id="type" class="custom_select">
                                                                    <?php   foreach ($this->objMarcas  as $obj) { 
                                                                                echo '<option value="'.$obj->getIdMarca().'">'.$obj->getNombre().'</option>';
                                                                            } ?>
								</select>
							</p>
							<p>
								<label for="category" class="dropdown_label">Version</label>
								<input type="text" placeholder="ej. GL" name="Modelo">
							</p>
                                                        <p>
								<label for="brand" class="dropdown_label">Cilindrada</label>
								<input type="text" placeholder="ej. 800" name="Modelo">
							</p>
                                                        <p>
								<label for="brand" class="dropdown_label">Kilometraje</label>
								<input type="text" placeholder="ej. 10000" name="Modelo">
							</p>
						</div>                                              
					</div>
                                       
					<div class="box-content clearfix">
						<div class="half left">
							<p>
								<label for="location" class="dropdown_label">Combustible</label>
								<select name="location" id="location" class="custom_select">
									<option value="">Bencina</option>
									<option value="">Disel</option>

								</select>
							</p>
						
							<p>
                                                            <label for="model" class="dropdown_label">Direcci&oacute;n</label>
								<select name="model" id="model" class="custom_select">
									<option value="">Mecanica</option>
									<option value="">Hidraulica</option>
									<option value="">Asistida</option>
			
								</select>
							</p>
                                                        <p><label for="negotiable" class="custom_checkbox"><input type="checkbox" name="negotiable" id="negotiable">AirBag</label></p>
                                                        <p><label for="negotiable" class="custom_checkbox"><input type="checkbox" name="negotiable" id="negotiable">4 WD</label></p>
                                                        <p><label for="negotiable" class="custom_checkbox"><input type="checkbox" name="negotiable" id="negotiable">Frenos ABS</label></p>
                                                        <p><label for="negotiable" class="custom_checkbox"><input type="checkbox" name="negotiable" id="negotiable">Aire acondicionado</label></p>
                                                        <p><label for="negotiable" class="custom_checkbox"><input type="checkbox" name="negotiable" id="negotiable">Espejos electricos</label></p>
                                                        <p><label for="negotiable" class="custom_checkbox"><input type="checkbox" name="negotiable" id="negotiable">Alzavidrios electricos</label></p>
                                                        <p><label for="negotiable" class="custom_checkbox"><input type="checkbox" name="negotiable" id="negotiable">Radio</label></p>
                                                        
                                                </div>
						<div class="half right">
							<p>
								<label for="transmision" class="dropdown_label">Transmision</label>
								<select name="transmision" id="transmision" class="custom_select">
									<option value="">Manual</option>
									<option value="">Semi-automatic</option>
									<option value="">Automatic</option>
								</select>
							</p>
						
							<p>
								<label for="fuel" class="dropdown_label">Traccion</label>
								<select name="fuel" id="fuel" class="custom_select">
									<option value="">Delantera</option>
									<option value="">Trasera</option>
									<option value="">4x4</option>
								</select>
							</p>
                                                        <p><label for="negotiable" class="custom_checkbox"><input type="checkbox" name="negotiable" id="negotiable">Catalitico</label></p>
                                                        <p><label for="negotiable" class="custom_checkbox"><input type="checkbox" name="negotiable" id="negotiable">LLantas</label></p>
                                                        <p><label for="negotiable" class="custom_checkbox"><input type="checkbox" name="negotiable" id="negotiable">Alarma</label></p>
                                                        <p><label for="negotiable" class="custom_checkbox"><input type="checkbox" name="negotiable" id="negotiable">Price is negotiable</label></p>
							<p><label for="negotiable" class="custom_checkbox"><input type="checkbox" name="negotiable" id="negotiable">Cierre centralizado</label></p>
                                                        <p><label for="negotiable" class="custom_checkbox"><input type="checkbox" name="negotiable" id="negotiable">Catalitico</label></p>
						</div>
					</div>
				</div>
				<div class="box">
					<h3>Descripcion</h3>
					<div class="box-content">
						<textarea name="description" id="description" placeholder="Enter your description"></textarea>
					</div>
				</div>
                                <div class="box">
					<h3>Opciones de venta</h3>
					<div class="box-content">
                                                <label for="brand" class="dropdown_label">Precio</label>
                                                <input type="text" placeholder="ej. 10000" name="Modelo">
						<p><label for="negotiable" class="custom_checkbox"><input type="checkbox" name="negotiable" id="negotiable">Precio negociable</label></p>
						<p><label for="exchange" class="custom_checkbox"><input type="checkbox" name="exchange" id="exchange">Posible permuta</label></p>
			
					</div>
				</div>
				<a class="button submit green">Publicar</a>
                               </form> 
			</div>
			<div class="grid_4">
				<div class="box">
					<h3>Agregar fotos</h3>
      
					<div class="box-content">
						<p>
                                                    <form class="centered_content" action="publicar/subirImagen" enctype="multipart/form-data" id="subirImagen">
                                                        <a class="button red" style="width: 157px;height: 55px;overflow: hidden;">
                                                            
                                                            Agregar Imagen
                                                            
                                                            <input name="imagen" type="file" id="imagen" class="button red" style="margin-left: -16px;margin-top:-37px;display: block !important;width: 157px !important;height: 55px !important; opacity: 0 !important;" />
                                                        </a>
                                                 
                                                    </form>
						</p>
                                                <div id="imagenbox">
                                                <p>
                                                    <div class="overlayed" id="imagen_box">
                                                      
                                                    </div>
                                                </p>
                                                </div>
					</div>
                                        
				</div>
	
				
			</div>
		
	</div>


<script type="text/javascript">
    $(document).ready(function(){
        var cont = "0";
        $('#imagen').change(function()
        {
            cont++;
            var formData = new FormData($("#subirImagen")[0]); 
            
            $.ajax({
                url: 'publicar/subirImagen',  
                type: 'POST',
                // Form data
                //datos del formulario
                data: formData,
                //necesario para subir archivos via ajax
                cache: false,
                contentType: false,
                processData: false,
                //mientras enviamos el archivo
                beforeSend: function(){
                    $("#imagen_box").append("<p><img id='cont"+cont+"' src='http://localhost/sinauto/public/img/cargando.gif'></p>");      
                },
                //una vez finalizado correctamente
                success: function(data){
                    if (data=="false") {
                        alert("error");
                        $("#cont"+cont+"").remove();
                    }else{
                        $("#cont"+cont+"").remove();
                        $("#imagen_box").append("<p><img id='cont"+cont+"' src='"+data+"'></p>");
                    }
     
                },
                //si ha ocurrido un error
                error: function(){
                    alert("error");
                    $("#cont"+cont+"").remove();
                }
            });
        });
    });

//como la utilizamos demasiadas veces, creamos una función para 
//evitar repetición de código
//comprobamos si el archivo a subir es una imagen
//para visualizarla una vez haya subido
function isImage(extension)
{
    switch(extension.toLowerCase()) 
    {
        case 'jpg': case 'gif': case 'png': case 'jpeg':
            return true;
        break;
        default:
            return false;
        break;
    }
}
</script>