

<div class="container_12 clearfix">
        <div class="grid_8 content">
                <section id="search">
                        <div class="tabbable tabbable_red">
                                <ul class="nav-tabs">
                                        <li class="active with_icon"><a href="#search_tab_1" data-toggle="tab"><i class="icomoon-search"></i>Search</a></li>
                                        <li class="with_icon"><a href="#search_tab_2" data-toggle="tab"><i class="icomoon-plus"></i>Add listing</a></li>
                                </ul>
                                <div class="tab-content">
                                        <div class="tab-pane active" id="search_tab_1">
                                                <form id="homepage_search" action="#">
                                                        <div class="row">
                                                                <div class="span6">
                                                                        <label for="type" class="dropdown_label">Type</label>
                                                                        <select name="type" id="type" class="custom_select">
                                                                                <option value="">Cars</option>
                                                                                <option value="">Motorcycles</option>
                                                                                <option value="">Trucks</option>
                                                                        </select>
                                                                </div>
                                                                <div class="span6">
                                                                        <label for="category" class="dropdown_label">Category</label>
                                                                        <select name="category" id="category" class="custom_select">
                                                                                <option value="">Sedan</option>
                                                                                <option value="">Hedgeback</option>
                                                                                <option value="">Pick-up</option>
                                                                        </select>
                                                                </div>
                                                        </div>
                                                        <div class="row second-row">
                                                                <div class="span6">
                                                                        <label for="condition_new" class="custom_radio custom_radio_light"><input type="radio" name="condition" id="condition_new" value="new">New items</label>
                                                                        <label for="condition_used" class="custom_radio custom_radio_light"><input type="radio" name="condition" id="condition_used" value="used">Used items</label>
                                                                </div>
                                                                <div class="span6 darker">
                                                                        <label for="with_photos" class="custom_checkbox custom_checkbox_light"><input type="checkbox" name="with_photos" id="with_photos">With photos</label>
                                                                        <label for="with_videos" class="custom_checkbox custom_checkbox_light"><input type="checkbox" name="with_videos " id="with_videos">With videos</label>
                                                                </div>
                                                        </div>
                                                        <div class="row">
                                                                <div class="span4">
                                                                        <label for="location" class="dropdown_label">Location</label>
                                                                        <select name="location" id="location" class="custom_select">
                                                                                <option value="">New York</option>
                                                                                <option value="">Chicago</option>
                                                                                <option value="">Washington</option>
                                                                                <option value="">Boston</option>
                                                                        </select>
                                                                </div>
                                                                <div class="span4">
                                                                        <label for="brand" class="dropdown_label">Brand</label>
                                                                        <select name="brand" id="brand" class="custom_select">
                                                                                <option value="">All</option>
                                                                                <option value="">BMW</option>
                                                                                <option value="">Mercedes</option>
                                                                                <option value="">Audi</option>
                                                                                <option value="">Ferrari</option>
                                                                        </select>
                                                                </div>
                                                                <div class="span4">
                                                                        <label for="model" class="dropdown_label">Model</label>
                                                                        <select name="model" id="model" class="custom_select">
                                                                                <option value="">All</option>
                                                                                <option value="">C</option>
                                                                                <option value="">E</option>
                                                                                <option value="">S</option>
                                                                                <option value="">CLK</option>
                                                                                <option value="">SLK</option>
                                                                        </select>
                                                                </div>
                                                        </div>
                                                        <div class="row last_row">
                                                                <div class="span6">
                                                                        <label for="price" class="dropdown_label">Price</label>
                                                                        <select name="price" id="price" class="custom_select range">
                                                                                <option value="">$5.000</option>
                                                                                <option value="">$10.000</option>
                                                                                <option value="">$15.000</option>
                                                                                <option value="">$20.000</option>
                                                                        </select>
                                                                        <span class="range_delimiter">-</span> 
                                                                        <select name="price_to" id="price_to" class="custom_select range">
                                                                                <option value="">$5.000</option>
                                                                                <option value="">$10.000</option>
                                                                                <option value="">$15.000</option>
                                                                                <option value="">$20.000</option>
                                                                        </select>
                                                                </div>
                                                                <div class="span6 clear_submit_buttons">
                                                                        <a href="#" class="clear_filters"><i class="icon-remove"></i> Clear filters</a>
                                                                        <a class="button submit yellow right">Search</a>
                                                                </div>
                                                        </div>
                                                </form>
                                        </div>
                                        <div class="tab-pane" id="search_tab_2">
                                                 Aenean pellentesque sollicitudin mi eu ultricies. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus nec elit nisl, quis gravida augue. Duis gravida purus sed nibh molestie eu congue elit pretium. In tellus risus, elementum quis consectetur in, mattis eget eros. Nullam et diam est, eget tempus quam. Donec vestibulum congue massa in feugiat. In hac habitasse platea dictumst. Nunc est dolor, dapibus ut ultricies nec, fringilla vitae metus. Curabitur ullamcorper, velit vitae aliquet consectetur, felis nibh ultrices nibh, sit amet consequat purus elit eget massa. Nunc adipiscing leo eget eros varius iaculis.
                                        </div>
                                </div>
                        </div>
                        <div class="label_under">
                                <p><a href="#">Advanced search</a></p>
                        </div>
                </section>	

                <section id="featured_items" class="clearfix">
                        <div class="tabbable">
                                <a href="#" class="help_link"><i class="icomoon-support"></i>Need Help?</a>
                                <ul class="nav-tabs">
                                        <li class="active"><a href="#featured_items_tab_1" data-toggle="tab">Used</a></li>
                                        <li><a href="#featured_items_tab_2" data-toggle="tab">New</a></li>
                                </ul>
                                <div class="tab-content">
                                        <div class="tab-pane active" id="featured_items_tab_1">
                                                <div class="half left featured_item">
                                                        <div class="overlayed">
                                                                <img src="<?php echo $_layoutParams['ruta_img']; ?>smart.jpg" alt="">
                                                                <div class="overlay">
                                                                        <span class="overlay-icon-single"><a href="item.html"><i class="icomoon-link"></i></a></span>
                                                                </div>
                                                        </div>
                                                        <h4>Smart <a href="item.html">Fortwo</a></h4>
                                                        <span class="item_year">2005</span>
                                                        <span class="item_engine">0,8</span>
                                                        <span class="item_price">$5,000</span>
                                                </div>
                                                <div class="half right">
                                                        <div class="item clearfix">
                                                                <div class="item_image">
                                                                        <div class="overlayed">
                                                                                <img src="<?php echo $_layoutParams['ruta_img']; ?>bentley.jpg" alt="">
                                                                                <div class="overlay">
                                                                                        <span class="overlay-icon-single"><a href="item.html"><i class="icomoon-link"></i></a></span>
                                                                                </div>
                                                                        </div>
                                                                </div>
                                                                <div class="item_meta">
                                                                        <h4>Bentley <a href="item.html">Continental</a></h4>
                                                                        <span class="item_year">2005</span>
                                                                        <span class="item_engine">6,0</span>
                                                                        <span class="item_price">$125,000</span>
                                                                </div>
                                                        </div>
                                                        <div class="item clearfix">
                                                                <div class="item_image">
                                                                        <div class="overlayed">
                                                                                <img src="<?php echo $_layoutParams['ruta_img']; ?>harley.jpg" alt="">
                                                                                <div class="overlay">
                                                                                        <span class="overlay-icon-single"><a href="item.html"><i class="icomoon-link"></i></a></span>
                                                                                </div>
                                                                        </div>
                                                                </div>
                                                                <div class="item_meta">
                                                                        <h4>Harley Davidson <a href="item.html">TP</a></h4>
                                                                        <span class="item_year">2005</span>
                                                                        <span class="item_engine">1,2</span>
                                                                        <span class="item_price">$25,000</span>
                                                                </div>
                                                        </div>
                                                        <div class="item clearfix">
                                                                <div class="item_image">
                                                                        <div class="overlayed">
                                                                                <img src="<?php echo $_layoutParams['ruta_img']; ?>cobra.jpg" alt="">
                                                                                <div class="overlay">
                                                                                        <span class="overlay-icon-single"><a href="item.html"><i class="icomoon-link"></i></a></span>
                                                                                </div>
                                                                        </div>
                                                                </div>
                                                                <div class="item_meta">
                                                                        <h4>Shelby <a href="item.html">Cobra 427</a></h4>
                                                                        <span class="item_year">2005</span>
                                                                        <span class="item_engine">7,0</span>
                                                                        <span class="item_price">$92,435</span>
                                                                </div>
                                                        </div>
                                                </div>
                                        </div>
                                        <div class="tab-pane" id="featured_items_tab_2">
                                                <div class="half left featured_item">
                                                        <div class="overlayed">
                                                                <img src="<?php echo $_layoutParams['ruta_img']; ?>bentley.jpg" alt="">
                                                                <div class="overlay">
                                                                        <span class="overlay-icon-single"><a href="item.html"><i class="icomoon-link"></i></a></span>
                                                                </div>
                                                        </div>
                                                        <h4>Bentley <a href="item.html">Continental</a></h4>
                                                        <span class="item_year">2005</span>
                                                        <span class="item_engine">6,0</span>
                                                        <span class="item_price">$125,000</span>
                                                </div>
                                                <div class="half right">
                                                        <div class="item clearfix">
                                                                <div class="item_image">
                                                                        <div class="overlayed">
                                                                                <img src="<?php echo $_layoutParams['ruta_img']; ?>cobra.jpg" alt="">
                                                                                <div class="overlay">
                                                                                        <span class="overlay-icon-single"><a href="item.html"><i class="icomoon-link"></i></a></span>
                                                                                </div>
                                                                        </div>
                                                                </div>
                                                                <div class="item_meta">
                                                                        <h4>Shelby <a href="item.html">Cobra 427</a></h4>
                                                                        <span class="item_year">2005</span>
                                                                        <span class="item_engine">7,0</span>
                                                                        <span class="item_price">$92,435</span>
                                                                </div>
                                                        </div>
                                                        <div class="item clearfix">
                                                                <div class="item_image">
                                                                        <div class="overlayed">
                                                                                <img src="<?php echo $_layoutParams['ruta_img']; ?>smart.jpg" alt="">
                                                                                <div class="overlay">
                                                                                        <span class="overlay-icon-single"><a href="item.html"><i class="icomoon-link"></i></a></span>
                                                                                </div>
                                                                        </div>
                                                                </div>
                                                                <div class="item_meta">
                                                                        <h4>Smart <a href="item.html">Fortwo</a></h4>
                                                                        <span class="item_year">2005</span>
                                                                        <span class="item_engine">0,8</span>
                                                                        <span class="item_price">$5,000</span>
                                                                </div>
                                                        </div>
                                                        <div class="item clearfix">
                                                                <div class="item_image">
                                                                        <div class="overlayed">
                                                                                <img src="<?php echo $_layoutParams['ruta_img']; ?>harley.jpg" alt="">
                                                                                <div class="overlay">
                                                                                        <span class="overlay-icon-single"><a href="item.html"><i class="icomoon-link"></i></a></span>
                                                                                </div>
                                                                        </div>
                                                                </div>
                                                                <div class="item_meta">
                                                                        <h4>Harley Davidson <a href="item.html">TP</a></h4>
                                                                        <span class="item_year">2005</span>
                                                                        <span class="item_engine">1,2</span>
                                                                        <span class="item_price">$25,000</span>
                                                                </div>
                                                        </div>
                                                </div>
                                        </div>
                                </div>
                        </div>
                </section>

                <section id="featured_news" class="clearfix">
                        <div class="tabbable">
                                <a href="blog.html" class="help_link">Go to blog</a>
                                <ul class="nav-tabs">
                                        <li class="active"><a href="#featured_news_tab_1" data-toggle="tab">News</a></li>
                                        <li><a href="#featured_news_tab_2" data-toggle="tab">Offers</a></li>
                                        <li><a href="#featured_news_tab_3" data-toggle="tab">Popular</a></li>
                                </ul>
                                <div class="tab-content">
                                        <div class="tab-pane active" id="featured_news_tab_1">
                                                <article class="featured_post clearfix">
                                                        <div class="half left">
                                                                <div class="overlayed">
                                                                        <img src="<?php echo $_layoutParams['ruta_img']; ?>tesla.jpg" alt="">
                                                                        <div class="overlay">
                                                                                <span class="overlay-icon-single"><a href="blog.html"><i class="icomoon-link"></i></a></span>
                                                                        </div>
                                                                </div>
                                                        </div>
                                                        <div class="half right">
                                                                <h4>Post with example</h4>
                                                                <span class="post_date">25 March, 2013</span>
                                                                <p>
                                                                        Maecenas porta velit consequat orci blandit adipiscing. Vivamus tempor sem vel elit ultricies convallis. Sed dictum lobortis risus sed fringilla.
                                                                </p>
                                                                <span class="blog_comments">11</span>
                                                        </div>
                                                </article>
                                                <div class="posts">
                                                        <div class="half left">
                                                                <article class="post clearfix">
                                                                        <div class="post_image">
                                                                                <div class="overlayed">
                                                                                        <img src="<?php echo $_layoutParams['ruta_img']; ?>jewelry.jpg" alt="">
                                                                                        <div class="overlay">
                                                                                                <span class="overlay-icon-single"><a href="blog.html"><i class="icomoon-link"></i></a></span>
                                                                                        </div>
                                                                                </div>
                                                                        </div>
                                                                        <div class="post_info">
                                                                                <h4><a href="single.html">Odit perferendis sunt</a></h4>
                                                                                <span class="post_date">25 March, 2013</span>
                                                                                <span class="blog_comments">45</span>
                                                                        </div>
                                                                </article>
                                                                <article class="post clearfix">
                                                                        <div class="post_image">
                                                                                <div class="overlayed">
                                                                                        <img src="<?php echo $_layoutParams['ruta_img']; ?>engine.jpg" alt="">
                                                                                        <div class="overlay">
                                                                                                <span class="overlay-icon-single"><a href="blog.html"><i class="icomoon-link"></i></a></span>
                                                                                        </div>
                                                                                </div>
                                                                        </div>
                                                                        <div class="post_info">
                                                                                <h4><a href="single.html">Ut, dolores, nisi</a></h4>
                                                                                <span class="post_date">25 March, 2013</span>
                                                                                <span class="blog_comments">1</span>
                                                                        </div>
                                                                </article>
                                                                <article class="post clearfix">
                                                                        <div class="post_image">
                                                                                <div class="overlayed">
                                                                                        <img src="<?php echo $_layoutParams['ruta_img']; ?>exhaust.jpg" alt="">
                                                                                        <div class="overlay">
                                                                                                <span class="overlay-icon-single"><a href="blog.html"><i class="icomoon-link"></i></a></span>
                                                                                        </div>
                                                                                </div>
                                                                        </div>
                                                                        <div class="post_info">
                                                                                <h4><a href="single.html">Consecte debitis quasi</a></h4>
                                                                                <span class="post_date">25 March, 2013</span>
                                                                                <span class="blog_comments">7</span>
                                                                        </div>
                                                                </article>
                                                        </div>
                                                        <div class="half right">
                                                                <article class="post clearfix">
                                                                        <div class="post_image">
                                                                                <div class="overlayed">
                                                                                        <img src="<?php echo $_layoutParams['ruta_img']; ?>tesla1.jpg" alt="">
                                                                                        <div class="overlay">
                                                                                                <span class="overlay-icon-single"><a href="blog.html"><i class="icomoon-link"></i></a></span>
                                                                                        </div>
                                                                                </div>
                                                                        </div>
                                                                        <div class="post_info">
                                                                                <h4><a href="single.html">Corrupti unde corpore</a></h4>
                                                                                <span class="post_date">25 March, 2013</span>
                                                                                <span class="blog_comments">31</span>
                                                                        </div>
                                                                </article>
                                                                <article class="post clearfix">
                                                                        <div class="post_image">
                                                                                <div class="overlayed">
                                                                                        <img src="<?php echo $_layoutParams['ruta_img']; ?>tesla2.jpg" alt="">
                                                                                        <div class="overlay">
                                                                                                <span class="overlay-icon-single"><a href="blog.html"><i class="icomoon-link"></i></a></span>
                                                                                        </div>
                                                                                </div>
                                                                        </div>
                                                                        <div class="post_info">
                                                                                <h4><a href="single.html">Sequi voluptatum</a></h4>
                                                                                <span class="post_date">25 March, 2013</span>
                                                                                <span class="blog_comments">14</span>
                                                                        </div>
                                                                </article>
                                                                <article class="post clearfix">
                                                                        <div class="post_image">
                                                                                <div class="overlayed">
                                                                                        <img src="<?php echo $_layoutParams['ruta_img']; ?>running-track.jpg" alt="">
                                                                                        <div class="overlay">
                                                                                                <span class="overlay-icon-single"><a href="blog.html"><i class="icomoon-link"></i></a></span>
                                                                                        </div>
                                                                                </div>
                                                                        </div>
                                                                        <div class="post_info">
                                                                                <h4><a href="single.html">Erchitecto repellat</a></h4>
                                                                                <span class="post_date">25 March, 2013</span>
                                                                                <span class="blog_comments">18</span>
                                                                        </div>
                                                                </article>
                                                        </div>
                                                </div>
                                        </div>
                                        <div class="tab-pane" id="featured_news_tab_2">
                                                <div class="posts">
                                                        <div class="half left">
                                                                <article class="post clearfix">
                                                                        <div class="post_image">
                                                                                <div class="overlayed">
                                                                                        <img src="<?php echo $_layoutParams['ruta_img']; ?>exhaust.jpg" alt="">
                                                                                        <div class="overlay">
                                                                                                <span class="overlay-icon-single"><a href="blog.html"><i class="icomoon-link"></i></a></span>
                                                                                        </div>
                                                                                </div>
                                                                        </div>
                                                                        <div class="post_info">
                                                                                <h4><a href="single.html">Consecte debitis quasi</a></h4>
                                                                                <span class="post_date">25 March, 2013</span>
                                                                                <span class="blog_comments">7</span>
                                                                        </div>
                                                                </article>
                                                                <article class="post clearfix">
                                                                        <div class="post_image">
                                                                                <div class="overlayed">
                                                                                        <img src="<?php echo $_layoutParams['ruta_img']; ?>running-track.jpg" alt="">
                                                                                        <div class="overlay">
                                                                                                <span class="overlay-icon-single"><a href="blog.html"><i class="icomoon-link"></i></a></span>
                                                                                        </div>
                                                                                </div>
                                                                        </div>
                                                                        <div class="post_info">
                                                                                <h4><a href="single.html">Erchitecto repellat</a></h4>
                                                                                <span class="post_date">25 March, 2013</span>
                                                                                <span class="blog_comments">18</span>
                                                                        </div>
                                                                </article>
                                                                <article class="post clearfix">
                                                                        <div class="post_image">
                                                                                <div class="overlayed">
                                                                                        <img src="<?php echo $_layoutParams['ruta_img']; ?>engine.jpg" alt="">
                                                                                        <div class="overlay">
                                                                                                <span class="overlay-icon-single"><a href="blog.html"><i class="icomoon-link"></i></a></span>
                                                                                        </div>
                                                                                </div>
                                                                        </div>
                                                                        <div class="post_info">
                                                                                <h4><a href="single.html">Ut, dolores, nisi</a></h4>
                                                                                <span class="post_date">25 March, 2013</span>
                                                                                <span class="blog_comments">1</span>
                                                                        </div>
                                                                </article>
                                                        </div>
                                                        <div class="half right">
                                                                <article class="post clearfix">
                                                                        <div class="post_image">
                                                                                <div class="overlayed">
                                                                                        <img src="<?php echo $_layoutParams['ruta_img']; ?>tesla.jpg" alt="">
                                                                                        <div class="overlay">
                                                                                                <span class="overlay-icon-single"><a href="blog.html"><i class="icomoon-link"></i></a></span>
                                                                                        </div>
                                                                                </div>
                                                                        </div>
                                                                        <div class="post_info">
                                                                                <h4><a href="single.html">Corrupti unde corpore</a></h4>
                                                                                <span class="post_date">25 March, 2013</span>
                                                                                <span class="blog_comments">31</span>
                                                                        </div>
                                                                </article>
                                                                <article class="post clearfix">
                                                                        <div class="post_image">
                                                                                <div class="overlayed">
                                                                                        <img src="<?php echo $_layoutParams['ruta_img']; ?>tesla2.jpg" alt="">
                                                                                        <div class="overlay">
                                                                                                <span class="overlay-icon-single"><a href="blog.html"><i class="icomoon-link"></i></a></span>
                                                                                        </div>
                                                                                </div>
                                                                        </div>
                                                                        <div class="post_info">
                                                                                <h4><a href="single.html">Sequi voluptatum</a></h4>
                                                                                <span class="post_date">25 March, 2013</span>
                                                                                <span class="blog_comments">14</span>
                                                                        </div>
                                                                </article>
                                                                <article class="post clearfix">
                                                                        <div class="post_image">
                                                                                <div class="overlayed">
                                                                                        <img src="<?php echo $_layoutParams['ruta_img']; ?>jewelry.jpg" alt="">
                                                                                        <div class="overlay">
                                                                                                <span class="overlay-icon-single"><a href="blog.html"><i class="icomoon-link"></i></a></span>
                                                                                        </div>
                                                                                </div>
                                                                        </div>
                                                                        <div class="post_info">
                                                                                <h4><a href="single.html">Odit perferendis sunt</a></h4>
                                                                                <span class="post_date">25 March, 2013</span>
                                                                                <span class="blog_comments">45</span>
                                                                        </div>
                                                                </article>
                                                        </div>
                                                </div>
                                        </div>
                                        <div class="tab-pane" id="featured_news_tab_3">
                                                <article class="featured_post clearfix">
                                                        <div class="half left">
                                                                <div class="overlayed">
                                                                        <img src="<?php echo $_layoutParams['ruta_img']; ?>jewelry.jpg" alt="">
                                                                        <div class="overlay">
                                                                                <span class="overlay-icon-single"><a href="blog.html"><i class="icomoon-link"></i></a></span>
                                                                        </div>
                                                                </div>
                                                        </div>
                                                        <div class="half right">
                                                                <h4>Post with example</h4>
                                                                <span class="post_date">25 March, 2013</span>
                                                                <p>
                                                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere dolorum sed asperiores iusto sapiente itaque dolorem ex labore quibusdam cupiditate!
                                                                </p>
                                                                <span class="blog_comments">4</span>
                                                        </div>
                                                </article>
                                                <article class="featured_post clearfix">
                                                        <div class="half left">
                                                                <div class="overlayed">
                                                                        <img src="<?php echo $_layoutParams['ruta_img']; ?>tesla.jpg" alt="">
                                                                        <div class="overlay">
                                                                                <span class="overlay-icon-single"><a href="blog.html"><i class="icomoon-link"></i></a></span>
                                                                        </div>
                                                                </div>
                                                        </div>
                                                        <div class="half right">
                                                                <h4>Consecte debitis quasi</h4>
                                                                <span class="post_date">25 March, 2013</span>
                                                                <p>
                                                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere dolorum sed asperiores iusto sapiente itaque dolorem ex labore quibusdam cupiditate!
                                                                </p>
                                                                <span class="blog_comments">4</span>
                                                        </div>
                                                </article>
                                        </div>
                                </div>
                        </div>
                </section>

        </div>
        <div class="grid_4 sidebar">
                <div class="row social_buttons">
                        <div class="span4">
                                <div id="fb-root"></div>
                                <script>(function(d, s, id) {
                                  var js, fjs = d.getElementsByTagName(s)[0];
                                  if (d.getElementById(id)) return;
                                  js = d.createElement(s); js.id = id;
                                  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
                                  fjs.parentNode.insertBefore(js, fjs);
                                }(document, 'script', 'facebook-jssdk'));</script>
                                <div class="fb-like" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false" data-font="lucida grande"></div>
                        </div>
                        <div class="span4">
                                <a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
                                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                        </div>
                        <div class="span4">
                                <div class="g-plusone" data-size="medium"></div>
                                <script type="text/javascript">
                                  (function() {
                                    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                                    po.src = 'https://apis.google.com/js/plusone.js';
                                    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
                                  })();
                                </script>
                        </div>
                </div>

                <div class="box">
                        <h3>Categories</h3>
                        <div class="box-content widget-categories">
                                <ul>
                                        <li><a href="#">Cars<span>23</span></a></li>
                                        <li><a href="#">Trucks<span>356</span></a></li>
                                        <li><a href="#">Motorbikes<span>45</span></a></li>
                                        <li><a href="#">Buses<span>71</span></a></li>
                                        <li><a href="#">Campers<span>18</span></a></li>
                                </ul> 
                        </div>
                </div>
                <div class="label_under">
                        <p><a href="#">View all categories</a></p>
                </div>

                <div class="box">
                        <h3>Online Support</h3>
                        <div class="box-content widget_online_support">
                                <div class="row">
                                        <img src="<?php echo $_layoutParams['ruta_img']; ?>johnsdoe.jpg" alt="" class="span6">
                                        <div class="span6">
                                                <span class="online_support_title">John S. Doe</span>
                                                <p>Integer nisl nunc, porta id sodales et, pulvinar et risus.</p>
                                </div></div>
                                <a href="#" class="button blue big wide"><i class="icomoon-volume-medium"></i>+1 (555) 555 - 35 - 55</a>
                                <a href="#">Contact Support Team</a><br>
                                <a href="#" class="link_light_gray">Learn more about <strong>Motor</strong></a>
                        </div>
                </div>

                <div class="box">
                        <h3>Newsletter Signup</h3>
                        <div class="box-content widget_newsletter">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, error?</p>
                                <form action="#">
                                        <input type="text" name="name" placeholder="Name">
                                        <input type="text" name="email" placeholder="Email">
                                        <p class="newsletter_checkbox"><label for="special_offers" class="custom_checkbox"><input type="checkbox" name="special_offers" id="special_offers"> Receive special offers</label></p>
                                        <p class="newsletter_button"><a class="button submit red wider">Signup</a>
                                </form>
                        </div>
                </div>

                <div class="box">
                        <h3>About Motor</h3>
                        <div class="box-content">
                                <p><strong>Ut in magna eget</strong> felis sodales ultrices. Aenean libero lacus, euismod sed tempus ut, vulputate ut nulla. Nulla facilisi. Pellentesque <a href="#">non augue vel</a> quam elementum consectetur.</p>
                        </div>
                </div>
        </div>
</div>

	